# action.yml
name: 'Hello World'
description: 'Greet someone with a "Hello, world!" message'
inputs:
  name:
    description: 'The name of the person to greet'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
